version: "3.8"
services:
  web:
    build: ./app
    image: 469292325435.dkr.ecr.us-east-1.amazonaws.com/devops-django-aws:devops-django-aws_web
    command: gunicorn learning_tracker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=learning_tracker_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=learning-tracker.cjeyubdnp5oe.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-52-0-11-54.compute-1.amazonaws.com
      - VIRTUAL_PORT=5432
  nginx:
    build: ./nginx
    image: 469292325435.dkr.ecr.us-east-1.amazonaws.com/devops-django-aws:devops-django-aws_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:
